language: node_js

env:
  - HBASE_VERSION=0.94.22

node_js:
  - "0.10"

before_script:
  - "export HBASE_FILE=hbase-$HBASE_VERSION"
  - "wget http://www.eu.apache.org/dist/hbase/hbase-$HBASE_VERSION/$HBASE_FILE.tar.gz"
  - "tar -xzf $HBASE_FILE.tar.gz"
  - "$HBASE_FILE/bin/start-hbase.sh"
  - "$HBASE_FILE/bin/hbase org.apache.hadoop.hbase.util.RegionSplitter test_table HexStringSplit -c 10 -f f:cf1"
